// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJPsEALdazAg5PuMfsh4AYhYDVYTBTlpQ',
    appId: '1:354292035943:web:0537e11da2c5cf2fce7fc2',
    messagingSenderId: '354292035943',
    projectId: 'healthier-f35d8',
    authDomain: 'healthier-f35d8.firebaseapp.com',
    storageBucket: 'healthier-f35d8.firebasestorage.app',
    measurementId: 'G-M5HN2KLPKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGGmIn-6p6BGR4Dp94Jt97OMuWJMN9XSk',
    appId: '1:354292035943:android:946eaba0423001a1ce7fc2',
    messagingSenderId: '354292035943',
    projectId: 'healthier-f35d8',
    storageBucket: 'healthier-f35d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO9HGshKpoR83ic4bA8hBrXR_Om3I1nKg',
    appId: '1:354292035943:ios:25879601eb101f97ce7fc2',
    messagingSenderId: '354292035943',
    projectId: 'healthier-f35d8',
    storageBucket: 'healthier-f35d8.firebasestorage.app',
    iosBundleId: 'com.example.healthier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO9HGshKpoR83ic4bA8hBrXR_Om3I1nKg',
    appId: '1:354292035943:ios:25879601eb101f97ce7fc2',
    messagingSenderId: '354292035943',
    projectId: 'healthier-f35d8',
    storageBucket: 'healthier-f35d8.firebasestorage.app',
    iosBundleId: 'com.example.healthier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJPsEALdazAg5PuMfsh4AYhYDVYTBTlpQ',
    appId: '1:354292035943:web:e15d1ba900a38eadce7fc2',
    messagingSenderId: '354292035943',
    projectId: 'healthier-f35d8',
    authDomain: 'healthier-f35d8.firebaseapp.com',
    storageBucket: 'healthier-f35d8.firebasestorage.app',
    measurementId: 'G-YKC4JQ01YT',
  );
}
